FROM debian:stable-slim

LABEL org.opencontainers.image.source="https://github.com/darkyzhou/seele" \
      org.opencontainers.image.url="https://github.com/darkyzhou/seele" \
      org.opencontainers.image.title="A utility image for seele"

ADD . /usr/local/bin
RUN chmod +x /usr/local/bin/diff-*